language: python
python:
  - "3.8"
dist: bionic
sudo: true
install:
  - pip install .
  - sudo apt-get install graphviz
  - pip install graphviz
script:
  - python -m pytest tests
notifications:
  email: false
